### ISSUE TITLE
Removed from CRAN

### ISSUE THREAD

**Issue by wibeasley** [richarddmorey/BayesSingleSub#1]
Hi @richarddmorey, Are you aware this package has been removed from CRAN?

 I get this message when I go to https://cran.r-project.org/package=BayesSingleSub

>Package ‘BayesSingleSub’ was removed from the CRAN repository.
>
>Formerly available versions can be obtained from the archive.
>
>Archived on 2019-07-02 as misuse of package= for PACKAGE= was not corrected despite reminder.

 I see it's been a few years since this has been updated.  If you're not interested in maintaining the package, do you have recommendations for a package with functionality similar to `BayesSingleSub::trendtest.Gibbs.AR()`?

**Comment by richarddmorey** [comment]
Ah, yes; this was my former PhD student's work and I moved it to GitHub so that it could be installed without CRAN (because I don't have time to keep up with CRAN's changes). Have you tried to install it from GitHub via devtools?

**Comment by wibeasley** [comment]
Thanks for the suggestion.  My CRAN package ([Wats](https://cran.rstudio.com/web/packages/Wats/index.html)) depends on it.  It's just the vignette though.

**Comment by richarddmorey** [comment]
Ah, I see. You can add it as under "remotes" in the DESCRIPTION file: https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html

**Comment by wibeasley** [comment]
@richarddmorey, it looks like I [can't use the `remotes` feature for CRAN packages](https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html).  I'll probably remove that analysis from the vignette and resubmit.  I'm kinda surprised that Ripley [removed my package](https://cran.r-project.org/package=Wats) with such short notice.  Fortunately it's a low-stakes package with no dependencies that few people will ever miss.

>### CRAN submission
>When you submit your package to CRAN, all of its dependencies must also be available on CRAN. For this reason, release() will warn you if you try to release a package with a Remotes field.

**Comment by richarddmorey** [comment]
These sort of things are why I'm trying to move away from CRAN...
